#!/bin/sh

uci -q batch <<-EOF01 >/dev/null
	delete firewall.timecontrol
	set firewall.timecontrol=include
	set firewall.timecontrol.type=script
	set firewall.timecontrol.path=/var/etc/timecontrol.include
	set firewall.timecontrol.reload=1
EOF01

uci -q batch <<-EOF02 >/dev/null
	delete ucitrack.@timecontrol[-1]
	add ucitrack timecontrol
	set ucitrack.@timecontrol[-1].init=timecontrol
	commit ucitrack
EOF02

rm -rf /tmp/luci-*cache
exit 0
